[package]
name = "leafwing_input_manager"
description = "A powerfully direct stateful input manager for the Bevy game engine."
version = "0.3.0"
authors = ["Leafwing Studios"]
homepage = "https://leafwing-studios.com/"
repository = "https://github.com/leafwing-studios/leafwing_input_manager"
license = "MIT OR Apache-2.0"
edition = "2021"
categories = ["games", "game-development"]
keywords = ["bevy"]
exclude = ["assets/**/*", "tools/**/*", ".github/**/*"]

[profile.dev]
opt-level = 3

[workspace]
members = ["./", "tools/ci", "macros"]

[dependencies]
bevy = {version = "0.6", default-features = false, features = ["render", "serialize"]}
petitset = {version = "0.2.1", features = ["serde_compat"]}
leafwing_input_manager_macros = "0.2"
leafwing_2d = "0.1"
thiserror = "1.0"
itertools = "0.10"
serde = {version = "1.0", features = ["derive"]}

[dev-dependencies]
bevy = {version = "0.6", default-features = true}
derive_more = "0.99"

[lib]
name = "leafwing_input_manager"
path = "src/lib.rs"

[patch.crates-io]
# Use for local development
#leafwing_input_manager_macros = {path = "./macros"}
leafwing_2d = {git = "https://github.com/leafwing-studios/leafwing_2d"}